version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 2s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactions
    deploy:
      resources:
        limits:
          cpus: '0.25'     # Limita a 25% de un CPU
          memory: 256M     # Limita a 256 MB de RAM
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3000
      PROVIDER: LOCAL
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: transactions
      ENV: DEV
    command: sh -c "npm run migration:run && npm start"
  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=
      - DD_SITE=us5.datadoghq.com
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_DATABASE_MONITORING_ENABLED=true
      - DD_ENV=dev
      - DD_SERVICE=merchant-transactions-api
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf.d/postgres.d:/etc/datadog-agent/conf.d/postgres.d
volumes:
  pgadmin-data: